// ignore_for_file: constant_identifier_names
/// country names as Enum
enum CppCountry {
  Afghanistan,
  Aland_Islands,
  Albania,
  Algeria,
  American_Samoa,
  Andorra,
  Angola,
  Anguilla,
  Antarctica,
  Antigua_And_Barbuda,
  Argentina,
  Armenia,
  Aruba,
  Australia,
  Austria,
  Azerbaijan,
  Bahamas_The,
  Bahrain,
  Bangladesh,
  Barbados,
  Belarus,
  Belgium,
  Belize,
  Benin,
  Bermuda,
  Bhutan,
  Bolivia,
  Bosnia_and_Herzegovina,
  Botswana,
  Bouvet_Island,
  Brazil,
  British_Indian_Ocean_Territory,
  Brunei,
  Bulgaria,
  Burkina_Faso,
  Burundi,
  Cambodia,
  Cameroon,
  Canada,
  Cape_Verde,
  Cayman_Islands,
  Central_African_Republic,
  Chad,
  Chile,
  China,
  Christmas_Island,
  Cocos_Keeling_Islands,
  Colombia,
  Comoros,
  Congo,
  Congo_The_Democratic_Republic_Of_The,
  Cook_Islands,
  Costa_Rica,
  Cote_D_Ivoire_Ivory_Coast,
  Croatia_Hrvatska,
  Cuba,
  Cyprus,
  Czech_Republic,
  Denmark,
  Djibouti,
  Dominica,
  Dominican_Republic,
  East_Timor,
  Ecuador,
  Egypt,
  El_Salvador,
  Equatorial_Guinea,
  Eritrea,
  Estonia,
  Ethiopia,
  Falkland_Islands,
  Faroe_Islands,
  Fiji_Islands,
  Finland,
  France,
  French_Guiana,
  French_Polynesia,
  French_Southern_Territories,
  Gabon,
  Gambia_The,
  Georgia,
  Germany,
  Ghana,
  Gibraltar,
  Greece,
  Greenland,
  Grenada,
  Guadeloupe,
  Guam,
  Guatemala,
  Guernsey_and_Alderney,
  Guinea,
  Guinea_Bissau,
  Guyana,
  Haiti,
  Heard_Island_and_McDonald_Islands,
  Honduras,
  Hong_Kong_S_A_R,
  Hungary,
  Iceland,
  India,
  Indonesia,
  Iran,
  Iraq,
  Ireland,
  Israel,
  Italy,
  Jamaica,
  Japan,
  Jersey,
  Jordan,
  Kazakhstan,
  Kenya,
  Kiribati,
  Korea_North,
  Korea_South,
  Kuwait,
  Kyrgyzstan,
  Laos,
  Latvia,
  Lebanon,
  Lesotho,
  Liberia,
  Libya,
  Liechtenstein,
  Lithuania,
  Luxembourg,
  Macau_S_A_R,
  Macedonia,
  Madagascar,
  Malawi,
  Malaysia,
  Maldives,
  Mali,
  Malta,
  Man_Isle_of,
  Marshall_Islands,
  Martinique,
  Mauritania,
  Mauritius,
  Mayotte,
  Mexico,
  Micronesia,
  Moldova,
  Monaco,
  Mongolia,
  Montenegro,
  Montserrat,
  Morocco,
  Mozambique,
  Myanmar,
  Namibia,
  Nauru,
  Nepal,
  Bonaire_Sint_Eustatius_and_Saba,
  Netherlands_The,
  New_Caledonia,
  New_Zealand,
  Nicaragua,
  Niger,
  Nigeria,
  Niue,
  Norfolk_Island,
  Northern_Mariana_Islands,
  Norway,
  Oman,
  Pakistan,
  Palau,
  Palestinian_Territory_Occupied,
  Panama,
  Papua_new_Guinea,
  Paraguay,
  Peru,
  Philippines,
  Pitcairn_Island,
  Poland,
  Portugal,
  Puerto_Rico,
  Qatar,
  Reunion,
  Romania,
  Russia,
  Rwanda,
  Saint_Helena,
  Saint_Kitts_And_Nevis,
  Saint_Lucia,
  Saint_Pierre_and_Miquelon,
  Saint_Vincent_And_The_Grenadines,
  Saint_Barthelemy,
  Saint_Martin_French_part,
  Samoa,
  San_Marino,
  Sao_Tome_and_Principe,
  Saudi_Arabia,
  Senegal,
  Serbia,
  Seychelles,
  Sierra_Leone,
  Singapore,
  Slovakia,
  Slovenia,
  Solomon_Islands,
  Somalia,
  South_Africa,
  South_Georgia,
  South_Sudan,
  Spain,
  Sri_Lanka,
  Sudan,
  Suriname,
  Svalbard_And_Jan_Mayen_Islands,
  Swaziland,
  Sweden,
  Switzerland,
  Syria,
  Taiwan,
  Tajikistan,
  Tanzania,
  Thailand,
  Togo,
  Tokelau,
  Tonga,
  Trinidad_And_Tobago,
  Tunisia,
  Turkey,
  Turkmenistan,
  Turks_And_Caicos_Islands,
  Tuvalu,
  Uganda,
  Ukraine,
  United_Arab_Emirates,
  United_Kingdom,
  United_States,
  United_States_Minor_Outlying_Islands,
  Uruguay,
  Uzbekistan,
  Vanuatu,
  Vatican_City_State_Holy_See,
  Venezuela,
  Vietnam,
  Virgin_Islands_British,
  Virgin_Islands_US,
  Wallis_And_Futuna_Islands,
  Western_Sahara,
  Yemen,
  Zambia,
  Zimbabwe,
  Kosovo,
  Curacao,
  Sint_Maarten_Dutch_part
}

/// countries map List
const Map<CppCountry, int> Countries = {
  CppCountry.Afghanistan: 0,
  CppCountry.Aland_Islands: 1,
  CppCountry.Albania: 2,
  CppCountry.Algeria: 3,
  CppCountry.American_Samoa: 4,
  CppCountry.Andorra: 5,
  CppCountry.Angola: 6,
  CppCountry.Anguilla: 7,
  CppCountry.Antarctica: 8,
  CppCountry.Antigua_And_Barbuda: 9,
  CppCountry.Argentina: 10,
  CppCountry.Armenia: 11,
  CppCountry.Aruba: 12,
  CppCountry.Australia: 13,
  CppCountry.Austria: 14,
  CppCountry.Azerbaijan: 15,
  CppCountry.Bahamas_The: 16,
  CppCountry.Bahrain: 17,
  CppCountry.Bangladesh: 18,
  CppCountry.Barbados: 19,
  CppCountry.Belarus: 20,
  CppCountry.Belgium: 21,
  CppCountry.Belize: 22,
  CppCountry.Benin: 23,
  CppCountry.Bermuda: 24,
  CppCountry.Bhutan: 25,
  CppCountry.Bolivia: 26,
  CppCountry.Bosnia_and_Herzegovina: 27,
  CppCountry.Botswana: 28,
  CppCountry.Bouvet_Island: 29,
  CppCountry.Brazil: 30,
  CppCountry.British_Indian_Ocean_Territory: 31,
  CppCountry.Brunei: 32,
  CppCountry.Bulgaria: 33,
  CppCountry.Burkina_Faso: 34,
  CppCountry.Burundi: 35,
  CppCountry.Cambodia: 36,
  CppCountry.Cameroon: 37,
  CppCountry.Canada: 38,
  CppCountry.Cape_Verde: 39,
  CppCountry.Cayman_Islands: 40,
  CppCountry.Central_African_Republic: 41,
  CppCountry.Chad: 42,
  CppCountry.Chile: 43,
  CppCountry.China: 44,
  CppCountry.Christmas_Island: 45,
  CppCountry.Cocos_Keeling_Islands: 46,
  CppCountry.Colombia: 47,
  CppCountry.Comoros: 48,
  CppCountry.Congo: 49,
  CppCountry.Congo_The_Democratic_Republic_Of_The: 50,
  CppCountry.Cook_Islands: 51,
  CppCountry.Costa_Rica: 52,
  CppCountry.Cote_D_Ivoire_Ivory_Coast: 53,
  CppCountry.Croatia_Hrvatska: 54,
  CppCountry.Cuba: 55,
  CppCountry.Cyprus: 56,
  CppCountry.Czech_Republic: 57,
  CppCountry.Denmark: 58,
  CppCountry.Djibouti: 59,
  CppCountry.Dominica: 60,
  CppCountry.Dominican_Republic: 61,
  CppCountry.East_Timor: 62,
  CppCountry.Ecuador: 63,
  CppCountry.Egypt: 64,
  CppCountry.El_Salvador: 65,
  CppCountry.Equatorial_Guinea: 66,
  CppCountry.Eritrea: 67,
  CppCountry.Estonia: 68,
  CppCountry.Ethiopia: 69,
  CppCountry.Falkland_Islands: 70,
  CppCountry.Faroe_Islands: 71,
  CppCountry.Fiji_Islands: 72,
  CppCountry.Finland: 73,
  CppCountry.France: 74,
  CppCountry.French_Guiana: 75,
  CppCountry.French_Polynesia: 76,
  CppCountry.French_Southern_Territories: 77,
  CppCountry.Gabon: 78,
  CppCountry.Gambia_The: 79,
  CppCountry.Georgia: 80,
  CppCountry.Germany: 81,
  CppCountry.Ghana: 82,
  CppCountry.Gibraltar: 83,
  CppCountry.Greece: 84,
  CppCountry.Greenland: 85,
  CppCountry.Grenada: 86,
  CppCountry.Guadeloupe: 87,
  CppCountry.Guam: 88,
  CppCountry.Guatemala: 89,
  CppCountry.Guernsey_and_Alderney: 90,
  CppCountry.Guinea: 91,
  CppCountry.Guinea_Bissau: 92,
  CppCountry.Guyana: 93,
  CppCountry.Haiti: 94,
  CppCountry.Heard_Island_and_McDonald_Islands: 95,
  CppCountry.Honduras: 96,
  CppCountry.Hong_Kong_S_A_R: 97,
  CppCountry.Hungary: 98,
  CppCountry.Iceland: 99,
  CppCountry.India: 100,
  CppCountry.Indonesia: 101,
  CppCountry.Iran: 102,
  CppCountry.Iraq: 103,
  CppCountry.Ireland: 104,
  CppCountry.Israel: 105,
  CppCountry.Italy: 106,
  CppCountry.Jamaica: 107,
  CppCountry.Japan: 108,
  CppCountry.Jersey: 109,
  CppCountry.Jordan: 110,
  CppCountry.Kazakhstan: 111,
  CppCountry.Kenya: 112,
  CppCountry.Kiribati: 113,
  CppCountry.Korea_North: 114,
  CppCountry.Korea_South: 115,
  CppCountry.Kuwait: 116,
  CppCountry.Kyrgyzstan: 117,
  CppCountry.Laos: 118,
  CppCountry.Latvia: 119,
  CppCountry.Lebanon: 120,
  CppCountry.Lesotho: 121,
  CppCountry.Liberia: 122,
  CppCountry.Libya: 123,
  CppCountry.Liechtenstein: 124,
  CppCountry.Lithuania: 125,
  CppCountry.Luxembourg: 126,
  CppCountry.Macau_S_A_R: 127,
  CppCountry.Macedonia: 128,
  CppCountry.Madagascar: 129,
  CppCountry.Malawi: 130,
  CppCountry.Malaysia: 131,
  CppCountry.Maldives: 132,
  CppCountry.Mali: 133,
  CppCountry.Malta: 134,
  CppCountry.Man_Isle_of: 135,
  CppCountry.Marshall_Islands: 136,
  CppCountry.Martinique: 137,
  CppCountry.Mauritania: 138,
  CppCountry.Mauritius: 139,
  CppCountry.Mayotte: 140,
  CppCountry.Mexico: 141,
  CppCountry.Micronesia: 142,
  CppCountry.Moldova: 143,
  CppCountry.Monaco: 144,
  CppCountry.Mongolia: 145,
  CppCountry.Montenegro: 146,
  CppCountry.Montserrat: 147,
  CppCountry.Morocco: 148,
  CppCountry.Mozambique: 149,
  CppCountry.Myanmar: 150,
  CppCountry.Namibia: 151,
  CppCountry.Nauru: 152,
  CppCountry.Nepal: 153,
  CppCountry.Bonaire_Sint_Eustatius_and_Saba: 154,
  CppCountry.Netherlands_The: 155,
  CppCountry.New_Caledonia: 156,
  CppCountry.New_Zealand: 157,
  CppCountry.Nicaragua: 158,
  CppCountry.Niger: 159,
  CppCountry.Nigeria: 160,
  CppCountry.Niue: 161,
  CppCountry.Norfolk_Island: 162,
  CppCountry.Northern_Mariana_Islands: 163,
  CppCountry.Norway: 164,
  CppCountry.Oman: 165,
  CppCountry.Pakistan: 166,
  CppCountry.Palau: 167,
  CppCountry.Palestinian_Territory_Occupied: 168,
  CppCountry.Panama: 169,
  CppCountry.Papua_new_Guinea: 170,
  CppCountry.Paraguay: 171,
  CppCountry.Peru: 172,
  CppCountry.Philippines: 173,
  CppCountry.Pitcairn_Island: 174,
  CppCountry.Poland: 175,
  CppCountry.Portugal: 176,
  CppCountry.Puerto_Rico: 177,
  CppCountry.Qatar: 178,
  CppCountry.Reunion: 179,
  CppCountry.Romania: 180,
  CppCountry.Russia: 181,
  CppCountry.Rwanda: 182,
  CppCountry.Saint_Helena: 183,
  CppCountry.Saint_Kitts_And_Nevis: 184,
  CppCountry.Saint_Lucia: 185,
  CppCountry.Saint_Pierre_and_Miquelon: 186,
  CppCountry.Saint_Vincent_And_The_Grenadines: 187,
  CppCountry.Saint_Barthelemy: 188,
  CppCountry.Saint_Martin_French_part: 189,
  CppCountry.Samoa: 190,
  CppCountry.San_Marino: 191,
  CppCountry.Sao_Tome_and_Principe: 192,
  CppCountry.Saudi_Arabia: 193,
  CppCountry.Senegal: 194,
  CppCountry.Serbia: 195,
  CppCountry.Seychelles: 196,
  CppCountry.Sierra_Leone: 197,
  CppCountry.Singapore: 198,
  CppCountry.Slovakia: 199,
  CppCountry.Slovenia: 200,
  CppCountry.Solomon_Islands: 201,
  CppCountry.Somalia: 202,
  CppCountry.South_Africa: 203,
  CppCountry.South_Georgia: 204,
  CppCountry.South_Sudan: 205,
  CppCountry.Spain: 206,
  CppCountry.Sri_Lanka: 207,
  CppCountry.Sudan: 208,
  CppCountry.Suriname: 209,
  CppCountry.Svalbard_And_Jan_Mayen_Islands: 210,
  CppCountry.Swaziland: 211,
  CppCountry.Sweden: 212,
  CppCountry.Switzerland: 213,
  CppCountry.Syria: 214,
  CppCountry.Taiwan: 215,
  CppCountry.Tajikistan: 216,
  CppCountry.Tanzania: 217,
  CppCountry.Thailand: 218,
  CppCountry.Togo: 219,
  CppCountry.Tokelau: 220,
  CppCountry.Tonga: 221,
  CppCountry.Trinidad_And_Tobago: 222,
  CppCountry.Tunisia: 223,
  CppCountry.Turkey: 224,
  CppCountry.Turkmenistan: 225,
  CppCountry.Turks_And_Caicos_Islands: 226,
  CppCountry.Tuvalu: 227,
  CppCountry.Uganda: 228,
  CppCountry.Ukraine: 229,
  CppCountry.United_Arab_Emirates: 230,
  CppCountry.United_Kingdom: 231,
  CppCountry.United_States: 232,
  CppCountry.United_States_Minor_Outlying_Islands: 233,
  CppCountry.Uruguay: 234,
  CppCountry.Uzbekistan: 235,
  CppCountry.Vanuatu: 236,
  CppCountry.Vatican_City_State_Holy_See: 237,
  CppCountry.Venezuela: 238,
  CppCountry.Vietnam: 239,
  CppCountry.Virgin_Islands_British: 240,
  CppCountry.Virgin_Islands_US: 241,
  CppCountry.Wallis_And_Futuna_Islands: 242,
  CppCountry.Western_Sahara: 243,
  CppCountry.Yemen: 244,
  CppCountry.Zambia: 245,
  CppCountry.Zimbabwe: 246,
  CppCountry.Kosovo: 247,
  CppCountry.Curacao: 248,
  CppCountry.Sint_Maarten_Dutch_part: 249,
};
